Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Controllers/ImcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjetoFinal.Models;

namespace ProjetoFinal.Controllers
{
    public class ImcController : Controller
    {
        public IActionResult CalcularIMC(ImcModel Imc)
        {
            double CalcularIMC = Imc.CalcularIMC();
            if (CalcularIMC != 0) { 
            var imc = new ImcModel();
                {
                   // ViewData["mensagem"] = "ERROOOOOO";
                    //if (imc.CalcularIMC() >30)
                    //{
                    //    imc.Faixa = "vc esta abaixo do peso";
  
                    //}
                    /*else if (imc.CalcularIMC() >= 18.5 && imc.CalcularIMC() >= 24.9)
                    {
                        imc.Faixa = "vc no peso ideal";

                    }
                    else if (imc.CalcularIMC() >= 25 && imc.CalcularIMC() <= 29.9)
                    {
                        imc.Faixa = "vc esta sobre peso";

                    }
                    else if (imc.CalcularIMC() > 40)
                    {
                        imc.Faixa = "vc esta acima do peso";
                    }*/
                }
                



            }
            return View(Imc);


        }
        public IActionResult Imc()
        {
            var imc = new ImcModel();
           
            if (imc.CalcularIMC() <18.5000)
                 {
                  imc.Faixa = "abaixo";
                 }
            else if (imc.CalcularIMC() >= 18.5000 && imc.CalcularIMC() >= 24.9000)
                {
                    imc.Faixa = "ideal";
                }
            else if (imc.CalcularIMC() >= 25.0000 && imc.CalcularIMC() < 29.9000)
                {
                    imc.Faixa = "sobrepeso";
                }
            else if (imc.CalcularIMC() >= 40.000)
                {
                    imc.Faixa = "obeso";
                }
                
             else 
                    imc.Faixa = "ERROOOOO";

            ViewData["Faixa"] = imc.Faixa;
            return View();
        }
            
        }
    }

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto</title>

    <meta charset="UTF-8">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-gJWVjz180MvwCrGGkC4xE5FjhWkTxHIR/+GgT8j2B3KKMgh6waEjPgzzh7lL7JZT" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <style>
        body {
            background-color: #f7f7ff;
        }

        #tudo {
            margin: 0px 130px 0px 130px;
        }

        #formulario {
            margin: 20px 300px 0px 300px;
        }

        .btn1 {
            float: right;
        }
    </style>
    @Html.Raw(JavaScriptSnippet.FullScript)

</head>
<body onload="CarregarUsuarioLogado()">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" asp-controller="Home" asp-action="Index"> <i class="fa fa-stethoscope" aria-hidden="true"></i> Mais Saúde</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Home <i class="fa fa-home" aria-hidden="true"></i><span class="sr-only">(current)</span></a>
            </li>
        </ul>
        @using Microsoft.AspNetCore.Http;
        @inject IHttpContextAccessor HttpContextAccessor
        <form class="form-inline my-2 my-lg-0">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Usuario" asp-action="Login"><b>Login</b> <i class="fa fa-user-circle" aria-hidden="true"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Usuario" asp-action="CadastroUsuario">Cadastre-se!  <i class="fa fa-sign-out" aria-hidden="true"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">Política de Privacidade <i class="fa fa-users" aria-hidden="true"></i></a>
                </li>
            </ul>
        </form>
    </div>
</nav>
<!--FIM DO MENU-->

<div class="container body-content">
    @RenderBody()
    <hr />
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <footer>
        <p>&copy; 2018 - projetofinal</p>
    </footer>
</div>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
    <script>
        function CarregarUsuarioLogado() {
            var nome = '@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado")'

            if (nome != "") {
                var divNome = document.getElementById("NomeUsuarioLogado");
                divNome.innerHTML = "Olá, " + nome;

                var divLog = document.getElementById("log");
                divLog.innerHTML = "Logoff" + "<a href='../Usuario/Login/0'> </a>";

            }

            else {
                var divLog = document.getElementById("log");
                divLog.innerHTML = "Login";
            }

        }
    </script>
</body>
</html>

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Shared/_LayoutCadastro.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
   
</head>
<body style="background: linear-gradient(to bottom, #009999 37%, #ccffff 100%); height:57em; padding-top:5%;">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Mais Saúde</a>
            </div>
                              
    </nav>   
    <div class="container body-content">
        @RenderBody()
        <hr />
       
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

  
</body>
</html>

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Shared/_LayoutLogada.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto</title>

        <head>
            <meta charset="UTF-8">
            <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
            <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-gJWVjz180MvwCrGGkC4xE5FjhWkTxHIR/+GgT8j2B3KKMgh6waEjPgzzh7lL7JZT" crossorigin="anonymous">
            <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
            <style>
                body {
                    background-color: #f7f7ff;
                }

                #tudo {
                    margin: 0px 130px 0px 130px;
                }

                #formulario {
                    margin: 20px 300px 0px 300px;
                }

                .btn1 {
                    float: right;
                }
            </style>
            @Html.Raw(JavaScriptSnippet.FullScript)
        </head>
        <body onload="CarregarUsuarioLogado()">
            <!--MENU-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"> <i class="fa fa-stethoscope" aria-hidden="true"></i> Mais Saúde</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home <i class="fa fa-home" aria-hidden="true"></i><span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">Dietas <i class="fa fa-lemon-o" aria-hidden="true"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">Exercícios <i class="fa fa-heartbeat" aria-hidden="true"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">Receitas <i class="fa fa-cutlery" aria-hidden="true"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Imc" asp-action="Imc">Verificar IMC <i class="fa fa-medkit" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><b>Olá, Sarah!</b> <i class="fa fa-user-circle" aria-hidden="true"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Logoff  <i class="fa fa-sign-out" aria-hidden="true"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Política de Privacidade <i class="fa fa-users" aria-hidden="true"></i></a>
                            </li>
                        </ul>
                    </form>
                </div>
            </nav>
            @using Microsoft.AspNetCore.Http;
            @inject IHttpContextAccessor HttpContextAccessor
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - projetofinal</p>
            </footer>



    @RenderSection("Scripts", required: false)

    <script>
        function CarregarUsuarioLogado() {
            var nome = '@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado")'

            if (nome != "") {
                var divNome = document.getElementById("NomeUsuarioLogado");
                divNome.innerHTML = "Olá, " + nome;

                var divLog = document.getElementById("log");
                divLog.innerHTML = "Logoff" + "<a href='../Usuario/Login/0'> </a>";

            }

            else {
                var divLog = document.getElementById("log");
                divLog.innerHTML = "Login";
            }

        }
    </script>
</body>
</html>

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Shared/_LayoutLogado1.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)

</head>
<body onload="CarregarUsuarioLogado()" style="background: linear-gradient(to bottom, #009999 37%, #ccffff 100%); height:57em">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">


                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Exercícios
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="ExercicioAerobico">Aeróbicos</a></li>
                            <li><a href="ExercicioAnaerobico">Anaeróbicos</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Dietas
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="DietaH">Hipertensos</a></li>
                            <li><a href="DietaD">Diabéticos</a></li>
                        </ul>
                    </li>
                </ul>


                @using Microsoft.AspNetCore.Http;
                @inject IHttpContextAccessor HttpContextAccessor
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Logoff</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            *
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Editar conta</a></li>
                            <li><a href="#">Excluir conta</a></li>
                            <li><a href="#">Politica de privacidade</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - projetofinal</p>
        </footer>
    </div>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)

    <script>
        function CarregarUsuarioLogado() {
            var nome = '@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado")'

            if (nome != "") {
                var divNome = document.getElementById("NomeUsuarioLogado");
                divNome.innerHTML = "Olá, " + nome;

                var divLog = document.getElementById("log");
                divLog.innerHTML = "Logoff" + "<a href='../Usuario/Login/0'> </a>";

            }

            else {
                var divLog = document.getElementById("log");
                divLog.innerHTML = "Login";
            }

        }
    </script>
</body>
</html>

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Shared/_LayoutLogin.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script href="~/js/site.js"></script>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
   
</head>
<body onload="CarregarUsuarioLogado()" style="background: linear-gradient(to bottom, #009999 37%, #ccffff 100%); height:57em; padding-top:10%;">
    @using Microsoft.AspNetCore.Http;
    @inject IHttpContextAccessor HttpContextAccessor
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Mais Saúde</a>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
    <script>
        function CarregarUsuarioLogado() {
            var nome =@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado")
            if(nome != "") {
                var divnome = document.getElementById("NomeUsuarioLogado");
                divNome.innerHTML = "Olá" + nome;

                var divLog = Document.getElementById("log");
                divLog.innerHTMAL="<a href ='..Usuario/Login/0'> Logoff </a>"

            }

        }
    </script>


</body>
</html>