Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Controllers/PressaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoFinal.Models;

namespace ProjetoFinal.Controllers
{
    public class PressaoController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;
        public PressaoController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;

        }
        public IActionResult Usuario_Logado(int cpf)
        {
            PressaoModel objPressao = new PressaoModel(HttpContextAccessor);
            ViewBag.listaPressao = objPressao.ListaPressao();
            return View();

        }
        [HttpPost]
        public IActionResult Pressao(PressaoModel formulario)
        {
            if (ModelState.IsValid)
            {
                //formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.InserirPressao();
                return RedirectToAction("UsuarioLogado");
            }
            return View();
        }
        [HttpGet]
        public IActionResult ExcluirPressao(int Cpf)
        {
            PressaoModel objPressao = new PressaoModel(HttpContextAccessor);
            objPressao.Excluir(Cpf);
            return RedirectToAction("UsuarioLogado");
        }
    }
}

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Pressao/Pressao.cshtml
@model PressaoModel
@{
    Layout = "../Shared/_LayoutLogada.cshtml";
}

<div class="container menu">
    <h3> Meu grafico semanal</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th> Cpf</th>
                <th> Nivel glicemico</th>
                <th>  Data de inserção</th>

            </tr>
        </thead>

    </table>
    @{
        foreach (var item in (List<PressaoModel>)ViewBag.ListaPressao)
        {
            <body>
                <tr>
                    <td> @item.Cpf.ToString()</td>
                    <td> @item.Pressao.ToString()</td>
                    <td> @item.data_cadastro.ToString()</td>
                    <td>
                        <button type"button" class="btn btn-danger  btn-sm" onclick="Editar(@item.Cpf.ToString())">
                            <spam class="glyphicon glyphicon-edit"></spam>
                        </button>

                        <button type="button" class="btn btn-info btn-sm" onclick="Excluir(@item.Cpf.ToString())">
                            <span class="glyphicon glyphicon-trash"> </span>
                        </button>
                    </td>
                </tr>
            </body>
        }


    }
    <form asp-controller="Pressao" asp-action="Pressao" class="form-horizontal" style="margin-left:15%">
        <div class="form-group">
            <label class="control-label col-sm-2" for="nome">Cpf:</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" asp-for="Cpf" id="nome" placeholder="Informe seu cpf" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="cpf">Pressao:</label>
            <div class="col-sm-6">
                <input type="number" class="form-control" asp-for="Pressao" id="nome" placeholder="Informe sua Pressao" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="cpf">Nivel glicemico:</label>
            <div class="col-sm-6">
                <input type="datetime" class="form-control" asp-for="data_cadastro" id="nome">
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-3">
                <button type="submit" class="btn btn-block btn-info"> Ok</button>
            </div>
        </div>


    </form>
    <script>
        function Excluir(Cpf) {
            window.location.href = "../Pressao/ExcluirPressao" + Cpf;
        }
    </script>