Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoFinal.Models;

namespace ProjetoFinal.Controllers
{
    public class GraficoController : Controller
    {
       
        
            IHttpContextAccessor HttpContextAccessor;

            public GraficoController(IHttpContextAccessor httpContextAccessor)
            {
                HttpContextAccessor = httpContextAccessor;
            }

            public IActionResult Grafico()
            {
                GraficoModel objTransacao = new GraficoModel(HttpContextAccessor);
                ViewBag.ListaGrafico= objTransacao.ListaGrafico();
                return View();
            }

            [HttpPost]
            public IActionResult Registrar(GraficoModel formulario)
            {
                if (ModelState.IsValid)
                {
                    formulario.HttpContextAccessor = HttpContextAccessor;
                    formulario.Insert();
                    return RedirectToAction("Index");
                }

                return View();
            }

            [HttpGet]
            public IActionResult Registrar(int? id)
            {
                if (id != null)
                {
                    GraficoModel objTransacao = new GraficoModel(HttpContextAccessor);
                    ViewBag.Registro = objTransacao.CarregarRegistro(id);
                }
                ViewBag.ListaGrafico = new GlicemiaModel(HttpContextAccessor).ListaGlicemia();
                ViewBag.ListaPressao = new PressaoModel(HttpContextAccessor).ListaPressao();

                return View();
            }

            [HttpGet]
            public IActionResult Excluir(int id)
            {
                GraficoModel objTransacao = new GraficoModel(HttpContextAccessor);
                ViewBag.Registro = objTransacao.CarregarRegistro(id);
                return View();
            }


            [HttpGet]
            public IActionResult Excluirdados(int id)
            {
                GraficoModel objTransacao = new GraficoModel(HttpContextAccessor);
                objTransacao.Excluir(id);
                return RedirectToAction("UsuarioLogado");
            }

            [HttpGet]
            [HttpPost]
            public IActionResult Extrato(GraficoModel formulario)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                ViewBag.ListaGrafico = formulario.ListaGrafico();
                return View();
            }

            public IActionResult Dashboard()
            {
                List<Dashboard> lista = new Dashboard(HttpContextAccessor).RetornarDadosGraficoLine();
                string valores = "";
                string labels = "";
                string cores = "";
                var random = new Random();

                for (int i = 0; i < lista.Count; i++)
                {
                    valores += lista[i].Nivel_glicemico.ToString() + ",";
                    labels += "'" + lista[i].Data_cadastroG.ToString() + "',";
                    cores += "'" + String.Format("#{0:X6}", random.Next(0x1000000)) + "',";
                }

                ViewBag.Cores = cores;
                ViewBag.Labels = labels;
                ViewBag.Valores = valores;

                return View();
            }
        }
    }

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Grafico/Dashboard.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>

<div id="canvas-holder" style="width:60%">
    <canvas id="chart-area"></canvas>
</div>

<script>
    var randomScalingFactor = function () {
        return Math.round(Math.random() * 100);
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [@Html.Raw(ViewBag.Valores)],
                backgroundColor: [@Html.Raw(ViewBag.Cores)],
                label: 'Dataset 1'
            }],
            labels: [@Html.Raw(ViewBag.Labels)]
        },
        options: {
            responsive: true
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('chart-area').getContext('2d');
        window.myPie = new Chart(ctx, config);
    };

</script>

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Grafico/EditarDados.cshtml
<h3>Deseja Excluir o dado selecionada?</h3>

<p><strong>ID:</strong> @ViewBag.Registro.Id.ToString()</p>
<p><strong>Nivel glicemico:</strong> @ViewBag.Registro.Nivel_glicemico.ToString()</p>
<p><strong>Pressao:</strong> @ViewBag.Registro.Pressao.ToString()</p>
<p><strong>Data :</strong> @ViewBag.Registro.data_cadastroG.ToString()</p>
<p><strong>Data :</strong> @ViewBag.Registro.data_cadastroP.ToString()</p>
<p><strong>Codicao :</strong> @ViewBag.Registro.Valor.ToString()</p>


<button type="button" onclick="Cancelar()" class="btn btn-block btn-default">Cancelar</button>
<button type="button" onclick="Excluir(@ViewBag.Registro.Id.ToString())" class="btn btn-block btn-danger">Excluir</button>

<script>
    function Excluir(id) {
        window.location.href = "../../Grafico/Excluir/" + id;
    }

    function Cancelar() {
        window.location.href = "../../Grafico/Index";
    }
</script>

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Grafico/Grafico.cshtml
<h3>Meus Dados</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            
            <th>ID</th>
            <th>Data</th>
            <th>Nivel glicemico</th>
            <th>Pressao</th>
           
        </tr>
    </thead>

    @{
        foreach (var item in (List<GraficoModel>)ViewBag.ListaGrafico)
        {
            <tbody>
                <tr>
                    <td><button type="button" class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
                    <td>@item.Id.ToString()</td>
                    <td>@item.Data_cadastroP.ToString()</td>
                    <td>@item.Data_cadastroG.ToString()</td>
                    <td>@item.Nivel_glicemico.ToString().Replace("H", "Hipertenso").Replace("D", "Diabetico")</td>
                    
                    <td>@item.Pressao.ToString()</td>
                    

                </tr>
            </tbody>
        }
    }

</table>

<button type="button" class="btn btn-block btn-primary" onclick="Registrar()">Registrar Dados</button>

<script>
    function Registrar()
    {
        window.location.href = "../Grafico/Registrar";
    }

    function Excluirdados(id)
    {
        window.location.href = "../Grafico/Excluirdados/" + id;
    }

    function Editar(id) {
        window.location.href = "../Grafico/Registrar/" + id;
    }
</script>

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Grafico/Registrar.cshtml
@model GraficoModel


<h3>Registrar um novo dado</h3>

@{
    var vData = " ";
    var vPressao = "";
    var vNivel_glicemico = "";
    var vValor = 0.0;
    var vId = 0;
    var vCondicao = " ";

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vData = DateTime.Parse(@ViewBag.Registro.Data.ToString()).ToString("yyyy-MM-dd");
        vPressao = int.Parse(@ViewBag.Registro.Conta_Id.ToString());
        vNivel_glicemico = int.Parse(@ViewBag.Registro.Plano_Contas_Id.ToString());

        vValor = double.Parse(@ViewBag.Registro.Valor.ToString());
    }
    catch { }
}
<form asp-controller="Grafico" asp-action="Registrar">
    <input type="hidden" asp-for="Id" value="@vId" />

    <div class="form-group">
       
    </div>

    <div class="form-group">
        <label>Condicao:</label>

        @{
            
            if (vCondicao == "G")
            {
                <div class="radio"><label><input type="radio" asp-for="Condicao" value="G" checked>Nivel glicemico</label></div>
                <div class="radio"><label><input type="radio" asp-for="Condicao" value="H" unchecked>Pressao</label></div>
            }
            else
            {
                <div class="radio"><label><input type="radio" asp-for="Condicao" value="G" unchecked>Nivel glicemico</label></div>
                <div class="radio"><label><input type="radio" asp-for="Condicao" value="H" checked>Pressao</label></div>
            }
            if (vCondicao == "H")
            {
                <div class="radio"><label><input type="radio" asp-for="Condicao" value="H" checked>Nivel glicemico</label></div>
                <div class="radio"><label><input type="radio" asp-for="Condicao" value="G" unchecked>Pressao</label></div>
            }
            else
            {
                <div class="radio"><label><input type="radio" asp-for="Condicao" value="H" unchecked>Nivel glicemico</label></div>
                <div class="radio"><label><input type="radio" asp-for="Condicao" value="G" checked>Pressao</label></div>
            }
        }
    </div>

    <div class="form-group">
        <label>Valor:</label>
        <input type="number" class="form-control" asp-for="Valor" value="@vValor">
        <span asp-validation-for="Valor" class="text-danger"></span>
    </div>

  

    <div class="form-group">
        <label>Glicemia:</label>
        <select asp-for="Data_cadastroG" class="form-control">
            @{
               
                foreach (var item in (List<GlicemiaModel>)ViewBag.ListaGlicemia)
                {
                    if (item.Id.ToString() == vData.ToString())
                    {
                        <option selected value="@item.Id.ToString()">@item.Nivel_glicemico.ToString()</option>
                    }
                    else
                    {
                        <option value="@item.Id.ToString()">@item.Nivel_glicemico.ToString()</option>
                    }
                }
            }
        </select>
    </div>

    <div class="form-group">
        <label>Pressao:</label>
        <select asp-for="Id" class="form-control">
            @{
                foreach (var item in (List<PressaoModel>)ViewBag.ListaPressao)
                {
                    if (item.Id.ToString() == vId.ToString())
                    {
                        <option selected value="@item.Id.ToString()">@item.Pressao.ToString()</option>
                    }
                    else
                    {
                        <option value="@item.Id.ToString()">@item.Pressao.ToString()</option>

                    }
                }
            }
        </select>
    </div>

    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

Projeto Final/Estagio---Trio atualizado/ProjetoFinal/Views/Grafico/Resumo.cshtml
@model GraficoModel

<h3>Meu Perfil</h3>

<div class="container">
    <form asp-controller="Tipo de dado" asp-action="Perfil">
        <div class="form-group">
            <label>Valor:</label>
            <input type="text" asp-for="Valor" class="form-control">
        </div>
        <div class="form-group">
            <label>Tipo Transação:</label>
            <div class="radio"><label><input type="radio" asp-for="Nivel_glicemico" value="G" checked>Nivel glicemico</label></div>
            <div class="radio"><label><input type="radio" asp-for="Pressao" value="H">Pressao</label></div>

        </div>
        <button type="submit" class="btn btn-block btn-success">Pesquisar</button>
    </form>
</div>
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nível Glicêmico</th>
            <th>Pressão</th>
            <th>Data</th>
        </tr>
    </thead>

    @{
        var data = DateTime.Now;
        foreach (var item in (List<GraficoModel>)ViewBag.ListaGrafico)
        {
            <tbody>
                <tr>

                    <td> @item.Data_cadastroP=data</td>

                    <td> @item.Data_cadastroG=data</td>

                    <td><button type="button" class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                    
                    
                    <td>@item.Condicao.ToString()</td>
                    <td>R$ @item.Valor.ToString()</td>
                   </tr>

       
            </tbody>

            }
        }

</table>


<script>
    function Editar(id) {
        window.location.href = "../Grafico/Registrar/" + id;
    }
</script>